[release]
current-version = "0.0.1-alpha.2"

version-files = [
    "crates/seal_version/Cargo.toml",
    "crates/seal/Cargo.toml",
    { path = "dist-workspace.toml", field = "workspace.version", format = "cargo" }
]

commit-message = "Release v{version}"

branch-name = "release/v{version}"

push = true

create-pr = true

confirm = true
