[release]
current-version = "0.0.1-alpha.1"

version-files = ["crates/seal_version/Cargo.toml"]

commit-message = "Release v{version}"

branch-name = "release/v{version}"

tag-format = "v{version}"

push = true

create_pr = true

confirm = true
