[project]
site_name = "Seal"
site_url = "https://matthewmckee4.github.io/seal"
site_description = "A Release management tool, written in Rust"
site_author = "Matthew McKee"
repo_url = "https://github.com/MatthewMckee4/seal"
repo_name = "MatthewMckee4/seal"

docs_dir = "docs"
site_dir = "site"
dev_addr = "localhost:3000"

nav = [
    { "Home" = "index.md"},
    { "Configuration" = "configuration.md"},
    { "CLI" = "cli.md"},
]

[project.theme]
language = "en"
features = [
    "navigation.instant",
    "search.highlight"
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "custom"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "custom"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

features = [
    "announce.dismiss",
    # "content.code.annotate",
    # "content.code.copy",
    # "content.code.select",
    # "content.footnote.tooltips",
    # "content.tabs.link",
    # "content.tooltips",
    # "navigation.footer",
    # "navigation.indexes",
    "navigation.instant",
    # "navigation.instant.prefetch",
    # "navigation.path",
    # "navigation.sections",
    # "navigation.top",
    # "navigation.tracking",
    "search.highlight",
]

[project.markdown_extensions.pymdownx.highlight]
linenums = true
auto_title = true

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }
