[package]
name = "seal"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
seal_version = { workspace = true }

clap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anstream = { workspace = true }
anyhow = { workspace = true }
owo-colors = { workspace = true }
itertools = { workspace = true }
which = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0"
insta = { version = "1.41", features = ["filters", "json"] }
predicates = "3.1"
tempfile = "3.14"

[lints]
workspace = true
